version: "3.8"
services:
  server:
    build: .
    env_file:
      - server/.env
    ports:
      - 80:80
    depends_on:
      - db
  db:
    image: postgres:12.2-alpine
    env_file:
      - server/.env
    ports:
      - 5432:5432
